package com.hd.img;

import java.io.Serializable;

/**
 * Hzsyspersonnel generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("serial")
public class HdTabFtpServer implements Serializable {


	private String server_id;//FTP服务器id
	private String server_name;//FTP服务器名�?
	private String server_ip;//FTP服务器上传IP
	private String ftp_port;//FTP服务器端�?
	private String http_port;//HTTP服务器名�?
	private String join_date;//FTP服务器创建日�?
	private String ftp_user_name;//FTP服务器用户名
	private String ftp_user_password;//FTP服务器密�?
	private String ftp_user_folder;//FTP服务器文件夹
	private String server_out_ip;//下载Ip
	
	public String getServer_id() {
		return server_id;
	}
	public void setServer_id(String serverId) {
		server_id = serverId;
	}
	public String getServer_name() {
		return server_name;
	}
	public void setServer_name(String serverName) {
		server_name = serverName;
	}
	public String getServer_ip() {
		return server_ip;
	}
	public void setServer_ip(String serverIp) {
		server_ip = serverIp;
	}
	public String getFtp_port() {
		return ftp_port;
	}
	public void setFtp_port(String ftpPort) {
		ftp_port = ftpPort;
	}
	public String getHttp_port() {
		return http_port;
	}
	public void setHttp_port(String httpPort) {
		http_port = httpPort;
	}
	public String getJoin_date() {
		return join_date;
	}
	public void setJoin_date(String joinDate) {
		join_date = joinDate;
	}
	public String getFtp_user_name() {
		return ftp_user_name;
	}
	public void setFtp_user_name(String ftpUserName) {
		ftp_user_name = ftpUserName;
	}
	public String getFtp_user_password() {
		return ftp_user_password;
	}
	public void setFtp_user_password(String ftpUserPassword) {
		ftp_user_password = ftpUserPassword;
	}
	public String getFtp_user_folder() {
		return ftp_user_folder;
	}
	public void setFtp_user_folder(String ftpUserFolder) {
		ftp_user_folder = ftpUserFolder;
	}
	public String getServer_out_ip() {
		return server_out_ip;
	}
	public void setServer_out_ip(String server_out_ip) {
		this.server_out_ip = server_out_ip;
	}

	
	
	
	

}